### ISSUE TITLE
Binary doesn't work on ubuntu 16.04 ?

### ISSUE THREAD

**Issue by finlay** [stencila/dockter#27]
```
$ wget https://github.com/stencila/dockter/releases/download/v0.2.2/dockter-linux-x64.tar.gz
$ tar xvfz Downloads/dockter-linux-x64.tar.gz 
dockter
$ ./dockter build
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, lstat 'snapshot'
$ ./dockter -v
0.2.1
```

**Comment by nokome** [comment]
Can confirm this in a fresh `ubuntu:16.04` container started by....

```bash
docker run -it -v /var/run/docker.sock:/var/run/docker.sock ubuntu:16.04 bash
```
and Dockter installed...

```bash
apt-get update && apt-get install -y wget
wget https://github.com/stencila/dockter/releases/download/v0.2.2/dockter-linux-x64.tar.gz
tar xvfz dockter-linux-x64.tar.gz
```
Get...

```bash
root@0bc705ca7620:/# ./dockter --version
0.2.1
root@0bc705ca7620:/# ./dockter compile  
{}
root@0bc705ca7620:/# ./dockter build
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, lstat 'snapshot'
root@0bc705ca7620:/# 
```

**Comment by nokome** [comment]
To test this, instead of installing Dockter in the container, you can mount the local dev directory:

```bash
docker run -it -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/work ubuntu:16.04 bash
```

Then use the binary there:

```bash
root@ac046b7cad62:/# work/build/dockter-linux build
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, lstat 'snapshot'
```

Various experiments made me think this was not a packaging issues and instead an issue with trying to tar up a whole filesystem to send as the Docker build context but with a cryptic message. Indeed, I get the following when running the binary locally

```bash
nokome@pluto / [1]> ~/stencila/source/dockter/build/dockter-linux build
{ Error: EACCES: permission denied, scandir '/lost+found'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.fs.readdirSync (pkg/prelude/bootstrap.js:780:35)
    at exports.readdir (/snapshot/dockter/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/snapshot/dockter/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/snapshot/dockter/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at Readable.constructor.stream._read (/snapshot/dockter/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (_stream_readable.js:442:10)
    at readdirSync (/snapshot/dockter/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/snapshot/dockter/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/snapshot/dockter/node_modules/fast-glob/out/providers/reader-sync.js:61:24)
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/lost+found' }
```

Also get the same error when running from the uncompiled, unpackaged source code:

```bash
nokome@pluto ~/s/s/dockter (master)> npm run cli -- build /
```
