### ISSUE TITLE
fix(Windows): error when running compile

### ISSUE THREAD

**Issue by apawlik** [stencila/dockter#51]
```
{ Error: File 'C:\**\dockter\dist\PythonBuiltins.txt' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:422:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:650:29)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:693:18)
    at PythonParser.generateRequirementsFromSource (C:\snapshot\dockter\dist\PythonParser.js:115:48)
    at PythonParser.parse (C:\snapshot\dockter\dist\PythonParser.js:67:33)
    at DockerCompiler.compile (C:\snapshot\dockter\dist\DockerCompiler.js:56:46)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1308:13)
    at startup (bootstrap_node.js:227:16)
  errno: -4058,
  code: 'ENOENT',
  path: 'C:\\snapshot\\dockter\\dist\\PythonBuiltins.txt',
  pkg: true }
```

**Comment by nokome** [comment]
I'm glad you're dong this testing! I'm working on a fix now and will ping you when a new version is ready.

**Comment by nokome** [comment]
@apawlik @beneboy : just for future reference this is related to how `pkg` bundles up files into a binary - you need to specify anything that is not `.js`. See https://github.com/stencila/dockter/commit/11b8d07add2d16d56bc606ad2d9438320af9b380
