### ISSUE TITLE
NPM you cannot fetch versions for scoped packages

### ISSUE THREAD

**Issue by Keidrych** [stencila/dockter#87]
Easily reproduced: 
```
git@github.com:mcollina/hello-fastify.git
cd hello-fastify
dockter compile .
```
This occurs with more libraries than just this one, but any fastify project will fail because of it.
```
oops, sorry something went wrong :(
Please help us fix this issue by posting this output to https://github.com/stencila/dockter/issues/new
  args: compile .
  version: 0.14.2
  platform: darwin
{ HTTPError: Response code 401 (Unauthorized)
    at EventEmitter.module.exports.emitter.on (/snapshot/dockter/node_modules/got/source/as-promise.js:77:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'HTTPError',
  host: 'registry.npmjs.org',
  hostname: 'registry.npmjs.org',
  method: 'GET',
  path: '/@types/node/8.0.53',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://registry.npmjs.org/@types/node/8.0.53',
  statusCode: 401,
  statusMessage: 'Unauthorized',
  headers:
   { date: 'Fri, 22 Feb 2019 03:18:31 GMT',
     'transfer-encoding': 'chunked',
     connection: 'close',
     'set-cookie':
      [ '__cfduid=d66413d1c45fb69846449a3cd75e9aae51550805511; expires=Sat, 22-Feb-20 03:18:31 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
     'cf-ray': '4ace4e4f1917655d-SYD',
     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
     'npm-notice': 'ERROR: you cannot fetch versions for scoped packages',
     vary: 'Accept-Encoding',
     server: 'cloudflare' } }
```

**Comment by nokome** [comment]
@Keidrych : thanks for the bug report. Looks like we need to fetch `*`, instead of an explicit version, for any scoped package. e.g.

- https://registry.npmjs.org/@types%2fnode/8.0.53 : fails
- https://registry.npmjs.org/@types%2fnode/* : works

See https://github.com/npm/registry-issue-archive/issues/34#issuecomment-385420471 for an example of where others have has this issue.

Should be an easy fix - `if (name[0] === '@') version = '*'` just before https://github.com/stencila/dockter/blob/438dcd7fee7cfdd0dc2a31db17bb201d9f5ef3c6/src/JavascriptParser.ts#L125 perhaps?

**Comment by nokome** [comment]
Thanks again for the bug report. A fix has been made and is available in the latest release https://github.com/stencila/dockter/releases/tag/v0.14.3
